<a href="https://colab.research.google.com/github/mrunal028/HDS-Capstone/blob/main/src/EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("heart_attack_dataset.csv")

In [3]:
df.head()

,Age,Gender,Cholesterol,BloodPressure,HeartRate,BMI,Smoker,Diabetes,Hypertension,FamilyHistory,...,ExerciseInducedAngina,Slope,NumberOfMajorVessels,Thalassemia,PreviousHeartAttack,StrokeHistory,Residence,EmploymentStatus,MaritalStatus,Outcome
0,31,Male,194,162,71,22.9,0,1,0,0,...,Yes,Downsloping,1,Normal,0,0,Suburban,Retired,Single,No Heart Attack
1,69,Male,208,148,93,33.9,1,1,0,0,...,Yes,Upsloping,2,Normal,0,0,Suburban,Unemployed,Married,No Heart Attack
2,34,Female,132,161,94,34.0,0,0,1,1,...,Yes,Upsloping,0,Normal,1,0,Rural,Retired,Single,Heart Attack
3,53,Male,268,134,91,35.0,0,1,1,0,...,Yes,Flat,0,Reversible defect,1,0,Suburban,Retired,Widowed,No Heart Attack
4,57,Female,203,140,75,30.1,0,1,0,0,...,Yes,Flat,0,Fixed defect,1,0,Rural,Retired,Married,Heart Attack

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372974 entries, 0 to 372973
Data columns (total 32 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Age                    372974 non-null  int64
 1   Gender                 372974 non-null  object
 2   Cholesterol            372974 non-null  int64
 3   BloodPressure          372974 non-null  int64
 4   HeartRate              372974 non-null  int64
 5   BMI                    372974 non-null  float64
 6   Smoker                 372974 non-null  int64
 7   Diabetes               372974 non-null  int64
 8   Hypertension           372974 non-null  int64
 9   FamilyHistory          372974 non-null  int64
 10  PhysicalActivity       372974 non-null  int64
 11  AlcoholConsumption     372974 non-null  int64
 12  Diet                   372974 non-null  object
 13  StressLevel            372974 non-null  int64
 14  Ethnicity              372974 non-null  object
 15  Income                 372974 non-null  int64
 16  EducationLevel         372974 non-null  object
 17  Medication             372974 non-null  object
 18  ChestPainType          372974 non-null  object
 19  ECGResults             372974 non-null  object
 20  MaxHeartRate           372974 non-null  int64
 21  ST_Depression          372974 non-null  float64
 22  ExerciseInducedAngina  372974 non-null  object
 23  Slope                  372974 non-null  object
 24  NumberOfMajorVessels   372974 non-null  int64
 25  Thalassemia            372974 non-null  object
 26  PreviousHeartAttack    372974 non-null  int64
 27  StrokeHistory          372974 non-null  int64
 28  Residence              372974 non-null  object
 29  EmploymentStatus       372974 non-null  object
 30  MaritalStatus          372974 non-null  object
 31  Outcome                372974 non-null  object
dtypes: float64(2), int64(16), object(14)
memory usage: 91.1+ MB

In [4]:
# Basic information
print("Shape of dataset:", df.shape)

Shape of dataset: (372974, 32)

In [5]:
print("\nColumn data types:\n", df.dtypes)

Column data types:
 Age                        int64
Gender                    object
Cholesterol                int64
BloodPressure              int64
HeartRate                  int64
BMI                      float64
Smoker                     int64
Diabetes                   int64
Hypertension               int64
FamilyHistory              int64
PhysicalActivity           int64
AlcoholConsumption         int64
Diet                      object
StressLevel                int64
Ethnicity                 object
Income                     int64
EducationLevel            object
Medication                object
ChestPainType             object
ECGResults                object
MaxHeartRate               int64
ST_Depression            float64
ExerciseInducedAngina     object
Slope                     object
NumberOfMajorVessels       int64
Thalassemia               object
PreviousHeartAttack        int64
StrokeHistory              int64
Residence                 object
EmploymentStatus          object
MaritalStatus             object
Outcome                   object
dtype: object

In [6]:
# Basic information
print("\nMissing values:\n", df.isnull().sum())

Missing values:
 Age                      0
Gender                   0
Cholesterol              0
BloodPressure            0
HeartRate                0
BMI                      0
Smoker                   0
Diabetes                 0
Hypertension             0
FamilyHistory            0
PhysicalActivity         0
AlcoholConsumption       0
Diet                     0
StressLevel              0
Ethnicity                0
Income                   0
EducationLevel           0
Medication               0
ChestPainType            0
ECGResults               0
MaxHeartRate             0
ST_Depression            0
ExerciseInducedAngina    0
Slope                    0
NumberOfMajorVessels     0
Thalassemia              0
PreviousHeartAttack      0
StrokeHistory            0
Residence                0
EmploymentStatus         0
MaritalStatus            0
Outcome                  0
dtype: int64

In [8]:
df.describe()

,Age,Cholesterol,BloodPressure,HeartRate,BMI,Smoker,Diabetes,Hypertension,FamilyHistory,PhysicalActivity,AlcoholConsumption,StressLevel,Income,MaxHeartRate,ST_Depression,NumberOfMajorVessels,PreviousHeartAttack,StrokeHistory
count,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000,372974.000000
mean,56.975151,199.455844,134.508234,89.495043,29.006733,0.499225,0.500987,0.500973,0.499901,3.003475,2.000048,5.001885,110033.409913,149.463896,2.501799,1.498525,0.496938,0.500815
std,15.867016,57.723381,25.984528,17.342658,6.345460,0.500000,0.500000,0.500000,0.500001,2.000114,1.414572,2.582025,51961.721991,28.849990,1.443696,1.118003,0.499991,0.500000
min,30.000000,100.000000,90.000000,60.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,20000.000000,100.000000,0.000000,0.000000,0.000000,0.000000
25%,43.000000,149.000000,112.000000,74.000000,23.500000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,3.000000,64957.250000,124.000000,1.250000,0.000000,0.000000,0.000000
50%,57.000000,199.000000,134.000000,89.000000,29.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000,5.000000,110111.000000,149.000000,2.500000,1.000000,0.000000,1.000000
75%,71.000000,249.000000,157.000000,105.000000,34.500000,1.000000,1.000000,1.000000,1.000000,5.000000,3.000000,7.000000,155012.000000,174.000000,3.750000,2.000000,1.000000,1.000000
max,84.000000,299.000000,179.000000,119.000000,40.000000,1.000000,1.000000,1.000000,1.000000,6.000000,4.000000,9.000000,199999.000000,199.000000,5.000000,3.000000,1.000000,1.000000

In [9]:
# Categorical column summary
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    print(f"\nValue counts for {col}:\n", df[col].value_counts())

Value counts for Gender:
 Gender
Male      186770
Female    186204
Name: count, dtype: int64

Value counts for Diet:
 Diet
Moderate     125079
Healthy      124091
Unhealthy    123804
Name: count, dtype: int64

Value counts for Ethnicity:
 Ethnicity
White       74969
Asian       74942
Black       74532
Hispanic    74350
Other       74181
Name: count, dtype: int64

Value counts for EducationLevel:
 EducationLevel
High School     124912
College         124040
Postgraduate    124022
Name: count, dtype: int64

Value counts for Medication:
 Medication
No     186526
Yes    186448
Name: count, dtype: int64

Value counts for ChestPainType:
 ChestPainType
Asymptomatic    93609
Atypical        93262
Typical         93126
Non-anginal     92977
Name: count, dtype: int64

Value counts for ECGResults:
 ECGResults
LV hypertrophy      124750
ST-T abnormality    124227
Normal              123997
Name: count, dtype: int64

Value counts for ExerciseInducedAngina:
 ExerciseInducedAngina
No     186501
Yes    186473
Name: count, dtype: int64

Value counts for Slope:
 Slope
Flat           124546
Upsloping      124383
Downsloping    124045
Name: count, dtype: int64

Value counts for Thalassemia:
 Thalassemia
Normal               125106
Reversible defect    124071
Fixed defect         123797
Name: count, dtype: int64

Value counts for Residence:
 Residence
Suburban    124721
Rural       124336
Urban       123917
Name: count, dtype: int64

Value counts for EmploymentStatus:
 EmploymentStatus
Unemployed    124706
Retired       124373
Employed      123895
Name: count, dtype: int64

Value counts for MaritalStatus:
 MaritalStatus
Single      93599
Widowed     93467
Divorced    93094
Married     92814
Name: count, dtype: int64

Value counts for Outcome:
 Outcome
No Heart Attack    186658
Heart Attack       186316
Name: count, dtype: int64